apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cloud-engagement-hub
  namespace: openshift-marketplace
spec:
  displayName: Cloud Engagement Hub
  image: 'docker.io/ibmstocktrader/stocktrader-operator-catalog:v0.2.0'
  publisher: IBM
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: stocktrader-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: stocktrader-operator
  source: cloud-engagement-hub
  sourceNamespace: openshift-marketplace
  startingCSV: stocktrader-operator.v0.2.0
---
apiVersion: operators.ibm.com/v1
kind: StockTrader
metadata:
  name: ceh
spec:
  database:
    kind: db2
    db: BLUDB
    host: db2-connect-db2.devops-prereqs-44-a01ee4194ed985a1e32b1d96fd4ae346-0000.us-east.containers.appdomain.cloud
    id: db2inst1
    password: rkcY4t1Oyy7w281
    port: 30469
  global:
    auth: basic
    healthCheck: true
    ingress: false
    istio: false
    istioNamespace: mesh
    route: true
    jsonLogging: false
    monitoring: true
    specifyCerts: true
    certs: |
      -----BEGIN CERTIFICATE-----
      MIIDDzCCAfegAwIBAgIJANEH58y2/kzHMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV
      BAMME0lCTSBDbG91ZCBEYXRhYmFzZXMwHhcNMTgwNjI1MTQyOTAwWhcNMjgwNjIy
      MTQyOTAwWjAeMRwwGgYDVQQDDBNJQk0gQ2xvdWQgRGF0YWJhc2VzMIIBIjANBgkq
      hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8lpaQGzcFdGqeMlmqjffMPpIQhqpd8qJ
      Pr3bIkrXJbTcJJ9uIckSUcCjw4Z/rSg8nnT13SCcOl+1to+7kdMiU8qOWKiceYZ5
      y+yZYfCkGaiZVfazQBm45zBtFWv+AB/8hfCTdNF7VY4spaA3oBE2aS7OANNSRZSK
      pwy24IUgUcILJW+mcvW80Vx+GXRfD9Ytt6PRJgBhYuUBpgzvngmCMGBn+l2KNiSf
      weovYDCD6Vngl2+6W9QFAFtWXWgF3iDQD5nl/n4mripMSX6UG/n6657u7TDdgkvA
      1eKI2FLzYKpoKBe5rcnrM7nHgNc/nCdEs5JecHb1dHv1QfPm6pzIxwIDAQABo1Aw
      TjAdBgNVHQ4EFgQUK3+XZo1wyKs+DEoYXbHruwSpXjgwHwYDVR0jBBgwFoAUK3+X
      Zo1wyKs+DEoYXbHruwSpXjgwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
      AQEAJf5dvlzUpqaix26qJEuqFG0IP57QQI5TCRJ6Xt/supRHo63eDvKw8zR7tlWQ
      lV5P0N2xwuSl9ZqAJt7/k/3ZeB+nYwPoyO3KvKvATunRvlPBn4FWVXeaPsG+7fhS
      qsejmkyonYw77HRzGOzJH4Zg8UN6mfpbaWSsyaExvqknCp9SoTQP3D67AzWqb1zY
      doqqgGIZ2nxCkp5/FXxF/TMb55vteTQwfgBy60jVVkbF7eVOWCv0KaNHPF5hrqbN
      i+3XjJ7/peF3xMvTMoy35DcT3E2ZeSVjouZs15O90kI3k2daS2OHJABW0vSj4nLz
      +PQzp/B9cQmOO8dCe049Q3oaUA==
      -----END CERTIFICATE-----
  ingress:
    address: <your proxy node IP>:443
  jwt:
    audience: stock-trader
    issuer: http://stock-trader.ibm.com
  kafka:
    address: broker-1-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-4-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-3-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-0-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-2-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-5-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093
    apiKey: jLDci9EY7Vv27p5s0VWGDk-UWz4Br9Yb1LAdNhRQRuke
    topic: stocktrader
    user: token
  looper:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: rshrestha13/looper
      tag: latest
    url: http://{{ .Release.Name }}-looper-service:9080/looper
  broker:
    replicas: 2
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: rshrestha13/broker
      tag: latest
    url: http://{{ .Release.Name }}-broker-service:9080/broker
  account:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: rshrestha13/account
      tag: latest
    url: http://{{ .Release.Name }}-account-service:9080/account
  messaging:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/messaging
      tag: latest
    notification:
      url: http://{{ .Release.Name }}-notification-service:9080/notification
  cloudant:
    id: admin
    password: changeme
    url: https://couchdb-connect-cp4i.devops-prereqs-44-a01ee4194ed985a1e32b1d96fd4ae346-0000.us-east.containers.appdomain.cloud/
    apiKey: x5IiJ91ycorpEZJztgPCMQ9bQ26cQZwALO2Abgkn4XIT
    database: account
    collector: evidence
  collector:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/collector
      tag: latest
    url: http://{{ .Release.Name }}-collector-service:9080/collector
  ldap:
    baseDN: o=ibm.com
    host: bluepages.ibm.com
    port: 389
    realm: BluePages
  mongo:
    authDB: admin
    database: ibmclouddb
    ip: 915ce0b3-e08f-4aec-b58a-47e80442c6b4-0.blijs0dd0dcr4f55oehg.databases.appdomain.cloud
    port: 30926
    user: ibm_cloud_35228039_d73d_442a_9d48_6a5997dbfbce
    password: 53e01fea581f03613c851a4ca1928d8b348bbc9a4413c47f0e283eaeb78ffe18
  mq:
    channel: CLOUD.APP.SVRCONN
    host: qm1-4565.qm.us-south.mq.appdomain.cloud
    id: tradertest
    password: G3TLi9qk4iouH64wBv8zPpcRSUcTtY7s7pbr2CuxIklA
    port: 30341
    queue: NotificationQ
    queueManager: QM1
  notificationSlack:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/notification-slack
      tag: latest
  notificationTwitter:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/notification-twitter
      tag: latest
  odm:
    id: odmAdmin
    password: odmAdmin
    url: https://odm-connect-cp4a.devops-prereqs-44-a01ee4194ed985a1e32b1d96fd4ae346-0000.us-east.containers.appdomain.cloud/DecisionService/rest/v1/ICP_Trader_Dev_1/determineLoyalty
  oidc:
    clientId: <your client id>
    clientSecret: <your client secret>
    discoveryUrl: <your discovery url>
  openwhisk:
    id: bc2b0a37-0554-4658-9ebe-ae068eb1aa22
    password: 45t2FZC1q1bv6OYUztZUjkYFaVNs5klaviHoE6gFvgEedu9akiE1YW6lChOxUgJb
    url: https://openwhisk.ng.bluemix.net/api/v1/namespaces/jalcorn%40us.ibm.com_dev/actions/PostLoyaltyLevelToSlack
  portfolio:
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: rshrestha13/portfolio
      tag: mpRM
    url: http://{{ .Release.Name }}-portfolio-service:9080/portfolio
  redis:
    cacheInterval: 60
    urlWithCredentials: rediss://:520f2efd279cba2ac856eac98a8dfdcd15407a61a70a447ace8d52612b8db6e2@d34473b0-c94c-4093-a1e1-edc05b3c8596.blijti4d0v0nkr55oei0.databases.appdomain.cloud:30487/0
  s3:
    enabled: false
    bucket: stock-trader
    location: us
    endpointUrl: https://s3.us-east.cloud-object-storage.appdomain.cloud
    resourceInstanceId: >-
      crn:v1:bluemix:public:cloud-object-storage:global:a/b71ac2564ef0b98f1032d189795994dc:f7e4281d-a7f2-4923-8e6b-07f99ac93bbd::
    apiKey: tlqcyZem-fXIoRuyZinWtVGBGxvU6Zqd6QflQjI69IFr
  stockQuote:
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    apiConnect: https://api.us.apiconnect.ibmcloud.com/jalcornusibmcom-dev/sb/stocks
    iexApiKey: <your IEX API key>
    iexTrading: https://cloud.iexapis.com/stable/stock
    image:
      repository: rshrestha13/stock-quote
      tag: latest
    url: http://{{ .Release.Name }}-stock-quote-service:9080/stock-quote
  tradeHistory:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/trade-history
      tag: latest
    url: http://{{ .Release.Name }}-trade-history-service:9080/trade-history
  trader:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/trader
      tag: latest
  tradr:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/tradr
      tag: latest
  twitter:
    accessToken: 919153883989073920-xg257NoEkBjpgqw4bK8ntDX7jtQiwbC
    accessTokenSecret: J8y5xbH8vST5ZS3x2UJHCTOQBCABx3wlLgVVC4roGjdOh
    consumerKey: bP3wAYWySlBy60NQc3XUHRBt6
    consumerSecret: ATQze9DKqZz3OTKoDfAKXOesssy6MZ9qjo9Dq45a7YfRhvGXtq
  watson:
    id: apikey
    passwordOrApiKey: BCkUxgtSFAR-wI7G3fujWdkoVW6MaGWhV-byLKBKHes0
    url: https://api.us-south.tone-analyzer.watson.cloud.ibm.com/instances/195be178-5f78-467f-8355-99ee5772f4c2/v3/tone?version=2017-09-21&sentences=false
